# Compiler
CXX      = g++

# for GCOV (Testing coverage)
#CXXFLAGS+= -fprofile-arcs -ftest-coverage 

# Debugging ON/OFF (comment to disable)
CXXFLAGS+= -DDEBUG 	

CXXFLAGS+= `sdl2-config --cflags`

#includes for submodules
CXXFLAGS+= -I libs/imgui
CXXFLAGS+= -I libs/imgui/examples/libs/gl3w

#includes for non sub-modules libs
CXXFLAGS+= -I includes/

# Nodable header includes
CXXFLAGS+= -I sources
CXXFLAGS+= -I sources/Components
CXXFLAGS+= -I sources/Entities
CXXFLAGS+= -I sources/Common

CXXFLAGS+= -lGL -ldl
CXXFLAGS+= `sdl2-config --libs`
CXXFLAGS+= -std=c++11

LDFLAGS=
EXECUTABLE=nodable.bin

TARGET :=linux64

BINDIR :=bin/$(TARGET)
SRCDIR :=sources
OBJDIR :=build/$(TARGET)

# Nodable source files :
SOURCES := $(wildcard $(SRCDIR)/*.cpp)
SOURCES += $(wildcard $(SRCDIR)/Components/*.cpp)
SOURCES += $(wildcard $(SRCDIR)/Entities/*.cpp)
SOURCES += $(wildcard $(SRCDIR)/Common/*.cpp)

OBJECTS := $(patsubst $(SRCDIR)/%.cpp, $(OBJDIR)/%.o, $(SOURCES))
OBJECTS += libs/imgui/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.o
OBJECTS += libs/imgui/examples/libs/gl3w/GL/gl3w.o
OBJECTS += $(patsubst %.cpp, %.o, $(wildcard ./libs/imgui/*.cpp))

DEPENDENCIES := $(patsubst $(SRCDIR)/%.cpp, $(OBJDIR)/%.d, $(SOURCES))

all: makeFolders dependencies $(EXECUTABLE)

include $(wildcard $(OBJDIR)/*.d)

$(EXECUTABLE): $(OBJECTS)
	$(CXX)  $(OBJECTS) -o $(BINDIR)/$(EXECUTABLE) $(CXXFLAGS)

##############################################################
# Specific for imGui :
./libs/imgui/%.o: ./libs/imgui/%.cpp

libs/imgui/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.o : libs/imgui/examples/sdl_opengl3_example/imgui_impl_sdl_gl3.cpp
	$(CXX) -c $(CXXFLAGS) $< -o $@

libs/imgui/examples/libs/gl3w/GL/gl3w.o: libs/imgui/examples/libs/gl3w/GL/gl3w.c
	$(CXX) -c $(CXXFLAGS) $< -o $@
###############################################################"

# Build each object file
$(OBJDIR)/%.o: $(SRCDIR)/%.cpp $(OBJDIR)/%.d
	$(CXX) -c $(CXXFLAGS) $< -o $@

# This target creates a makefile per *.cpp (with all dependencies automatically generated by the compiler with -MM flag)
$(OBJDIR)/%.d : $(SRCDIR)/%.cpp
	@set -e; rm -f $@; \
	$(CXX) -MM $(CXXFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,$(OBJDIR)/\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$

# A target to run the program
.PHONY: run
run: all
	$(EXECUTABLE)

.PHONY: dependencies
dependencies: $(DEPENDENCIES)

.PHONY: makeFolders
makeFolders:
	mkdir -p $(OBJDIR)
	mkdir -p $(OBJDIR)/Components
	mkdir -p $(OBJDIR)/Entities
	mkdir -p $(OBJDIR)/Common
	mkdir -p $(BINDIR)
	mkdir -p $(BINDIR)/saves

.PHONY: clean
clean:
	rm -rf $(OBJECTS) $(DEPENDENCIES)

.PHONY: mrproper
mrproper: clean
	rm -rf $(EXEC)

