/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.32.10-0-g5d2495703 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.32.10-0-g5d2495703"
#endif
#define SDL_REVISION_NUMBER 0
