name: build

on:
  release:
    types:
      - created    
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04]

    env:
      # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
      buildType: Release
    
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
    - name: Git recursive checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get update && sudo apt-get install libsdl2-dev libegl1-mesa-dev doxygen

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.buildType}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{env.buildType}} --target install

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C ${{env.buildType}} --verbose

    - name: Upload binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: Nodable-${{ env.buildType }}-${{ runner.os }}
        path: ${{runner.workspace}}/Nodable/install/${{env.buildType}}

    - name: Generate documentation
      if: matrix.os == 'ubuntu-20.04'
      run: cd docs && doxygen

    - name: Upload documentation artifact
      if: matrix.os == 'ubuntu-20.04'
      uses: actions/upload-artifact@v2
      with:
        name: Nodable-Technical-Documentation
        path: ${{runner.workspace}}/Nodable/docs/doxygen
