name: "ci"

on:
  workflow_dispatch:
  release:
    types:
      - created
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-22.04]
    env:
      # Those are read by rake script
      BUILD_TYPE:  debug # release|debug
      VERBOSE: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`

      - name: Install Dependencies
        shell: bash
        run: rake install --trace

      - name: Build
        shell: bash
        run: rake build --trace

      - name: Test
        shell: bash
        run: rake test --trace

      - name: Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodable-${{ runner.os }}
          path: build-${{env.BUILD_TYPE}}/nodable