name: "ci"

on:
  workflow_dispatch:
  release:
    types:
      - created
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [windows-2025]
    env:
      # Those are read by rake script
      BUILD_TYPE:         release # release|debug
      BUILD_DIR:          ./out
      TARGET:             desktop # desktop|web
      VERBOSE:            true
      NDBL_SKIP_GUI_TEST: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4 # We don't rely on any submodule now, we use vcpkg (see ./vcpkg) and copy-pasted sources (see ./extern)

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.1' # Not needed with a `.ruby-version` or `.tool-versions`
      
      - name: Build
        # run: rake install # NOT REQUIRED since we add binaries to the sources
        run: rake build

      - name: Test
        run: rake test

      - name: Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodable-${{ env.TARGET }}-${{ env.BUILD_TYPE }}
          path: ./out/bin/

      # - name: Build
      #   if: env.TARGET == 'web'
      #   shell: bash
      #   run: source extern/emsdk/emsdk_env.sh && rake ndbl:build  
