name: "ci"

on:
  workflow_dispatch:
  release:
    types:
      - created
  push:
    branches: [master]
  pull_request:
    branches: [master]



jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        OS: [ windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.OS }}
    env:
      # Those are read by rake script
      BUILD_TYPE: release # release|debug
      BUILD_DIR: ./out
      TARGET: desktop # desktop|web
      VERBOSE: true
      NDBL_SKIP_GUI_TEST: true
      RAKE_FLAGS: "-j 1" # use 1 job to be able to read text outputs correctly when debugging
    steps:
      - uses: actions/checkout@v4 # no submodules (libs are in the sources, see ./vcpkg and ./extern)

      - run: rake ${{ env.RAKE_FLAGS }} install

      - run: rake ${{ env.RAKE_FLAGS }} build 

      - run: rake ${{ env.RAKE_FLAGS }} test

      - uses: actions/upload-artifact@v4
        with:
          name: nodable-${{ env.TARGET }}-${{ matrix.OS }}-${{ env.BUILD_TYPE }}
          path: ./out/bin/
