name: "ci"

on:
  workflow_dispatch:
  release:
    types:
      - created
  push:
    branches: [master]
  pull_request:
    branches: [master]



jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        # see https://github.com/actions/runner-images?tab=readme-ov-file
        includes:
          - platform: windows
            os: windows-2025-vs2026
          - platform: web
            os: windows-2025-vs2026 # do not change: tested on windows only
          - platform: linux
            os: ubuntu-24.04

    runs-on: ${{ matrix.includes.os }}
    env:
      PLATFORM:       ${{matrix.includes.platform}}
      CONFIG:         "release"
      BUILD_DIR:      "build"
      HEADLESS_TESTS: 1
    steps:
      - uses: actions/checkout@v4 # no submodules (libs are in the sources, see ./vcpkg and ./extern)
        with:
          fetch-tags:  true # Tag history is needed to generate nodable version and..
          fetch-depth: 100  # ..we also need some commits to generate the version name (uses `git describe --tags`), until now this value was enough.

      - run: rake install

      - if: env.PLATFORM == 'web'
        run: |
          extern/emsdk/emsdk_env.ps1
          rake build

      - if: env.PLATFORM != 'web'
        run: rake build

      - if: env.PLATFORM != 'web'
        run: ./tools-tests && ./nodable-tests
        working-directory: ${{env.BUILD_DIR}}/bin/ # must run tests in /bin/, tests are not copied in dist

      - run: rake nodable:zip

      - uses: actions/upload-artifact@v7
        with:
          name:    "nodable-${{env.PLATFORM}}"
          path:    "build/dist/nodable.zip"
          archive: false # This is already done