name: "Doxygen"

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Git recursive checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install doxygen

      - name: Generate documentation
        run: cd docs && doxygen

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: Nodable-Technical-Documentation
          path: ${{runner.workspace}}/Nodable/docs/doxygen
