name: linux

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: APT update
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install libsdl2-dev libegl1-mesa-dev
      
    - name: Configure CMake
      shell: bash
      run: cmake . -B build

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build build --config $BUILD_TYPE --target install

    - name: Test
      shell: bash
      run: ctest -C $BUILD_TYPE

    - uses: actions/upload-artifact@v2
      with:
        name: nodable-linux
        path: ./install
